export const subReddits = [
  { name: "r/pics", label: "Home" },
  { name: "r/technology", label: "Technology" },
  { name: "r/science", label: "Science" },
  { name: "r/worldnews", label: "Worldnews" },
  { name: "r/politics", label: "Politics" },
  { name: "r/business", label: "Business" },
  { name: "r/education", label: "Education" },
  { name: "r/environment", label: "Environment" },
  { name: "r/finance", label: "Finance" },
  { name: "r/AskReddit", label: "AskReddit" },
  { name: "r/space", label: "Space" },
  { name: "r/health", label: "Health" },
  { name: "r/food", label: "Food" },
  { name: "r/sports", label: "Sports" },
  { name: "r/music", label: "Music" },
  { name: "r/movies", label: "Movies" },
  { name: "r/books", label: "Books" },
  { name: "r/gaming", label: "Gaming" },
  { name: "r/art", label: "Art" },
  { name: "r/history", label: "History" },
  { name: "r/photography", label: "Photography" },
  { name: "r/travel", label: "Travel" },
  { name: "r/woahthatsinteresting", label: "Woah that's interesting" },
];